const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { spawnSync } = require('node:child_process');
const YAML = require('yaml');

const workflowPath = path.join(__dirname, '..', '.github', 'workflows', 'auto-update.yml');
const source = fs.readFileSync(workflowPath, 'utf8');
const workflow = YAML.parse(source);
const steps = workflow.jobs.release.steps;

function step(name) {
  return steps.find((item) => item.name === name);
}

test('release lookup steps target the current repo and tolerate an expected miss', () => {
  for (const name of [
    'Prepare candidate and inspect matching Release',
    'Create or reset draft Release',
  ]) {
    const run = step(name)?.run;
    assert.equal(typeof run, 'string', `missing workflow step: ${name}`);
    assert.match(run, /gh release view[^\r\n]*--repo \$\{\{ github\.repository \}\}/);
    assert.match(run, /try\s*\{\s*\r?\n\s*(?:\$release = )?gh release view[^\r\n]*2>\$null\s*\r?\n\s*\}\s*catch\s*\{/);
    assert.match(run, /\$LASTEXITCODE/);
    assert.match(run, /\$releaseLookupExit = \$LASTEXITCODE/);
    assert.match(run, /cmd \/c exit 0/);
    assert.match(run, /if\s*\(\$releaseLookupExit -eq 0\)/);
  }
});

test('draft asset steps query releases through gh release view', () => {
  for (const name of ['Upload candidate assets', 'Verify draft assets']) {
    const run = step(name)?.run;
    assert.equal(typeof run, 'string', `missing workflow step: ${name}`);
    assert.match(
      run,
      /gh release view \$env:TAG --repo \$\{\{ github\.repository \}\} --json assets\s*\|\s*ConvertFrom-Json/,
    );
    assert.doesNotMatch(run, /gh api[^\r\n]*\/releases\/tags\//);
  }
});

test('mutating release commands remain outside tolerated lookup failures', () => {
  const run = step('Create or reset draft Release')?.run;
  assert.match(run, /gh release edit/);
  assert.match(run, /gh release create/);
  assert.doesNotMatch(run, /try\s*\{[\s\S]*gh release (?:edit|create)[\s\S]*\}\s*catch/);
});

test('both release probes preserve and reset the native exit status', () => {
  assert.equal((source.match(/\$releaseLookupExit = \$LASTEXITCODE/g) || []).length, 2);
  assert.equal((source.match(/cmd \/c exit 0/g) || []).length, 2);
});

test('clean verified build disables implicit publishing and fails fast', () => {
  const run = step('Clean verified build')?.run;
  assert.equal(typeof run, 'string');
  assert.deepEqual(run.trim().split(/\r?\n/).map((line) => line.trim()), [
    'npm ci',
    "if ($LASTEXITCODE -ne 0) { throw 'npm ci failed' }",
    'npm test',
    "if ($LASTEXITCODE -ne 0) { throw 'npm test failed' }",
    'npm run build -- --publish never',
    "if ($LASTEXITCODE -ne 0) { throw 'package build failed' }",
    'npm run verify:package',
    "if ($LASTEXITCODE -ne 0) { throw 'package verification failed' }",
    'npm run smoke:package',
    "if ($LASTEXITCODE -ne 0) { throw 'package smoke failed' }",
  ]);
});

test('package contract accepts exact upstream candidates generated by the workflow', () => {
  const packagePath = path.join(__dirname, '..', 'package.json');
  const contractPath = path.join(__dirname, 'package-contract.test.js');
  const script = `
    const packagePath = process.argv[1], contractPath = process.argv[2];
    const pkg = require(packagePath);
    require.cache[packagePath].exports = {
      ...pkg,
      version: '9.9.9',
      dependencies: {
        ...pkg.dependencies,
        '@agegr/pi-web': '8.8.8',
        '@earendil-works/pi-coding-agent': '7.7.7',
      },
    };
    require(contractPath);
  `;
  const result = spawnSync(process.execPath, ['-e', script, packagePath, contractPath], {
    encoding: 'utf8',
    timeout: 30000,
  });
  assert.ifError(result.error);
  assert.equal(result.status, 0, result.stderr || result.stdout);
  const tests = Number(result.stdout.match(/\btests\s+(\d+)/)?.[1]);
  const passed = Number(result.stdout.match(/\bpass\s+(\d+)/)?.[1]);
  assert.equal(Number.isInteger(tests) && tests > 0, true, result.stdout);
  assert.equal(passed, tests, result.stdout);
});
